### ISSUE TITLE
Slim's birthday

### ISSUE THREAD

**Issue by slimbaccouch** [hafedh-hichri/web-scraping-enetcom#1]
![EuBOupZXEAAYPOe](https://user-images.githubusercontent.com/75909979/220142951-58a3c320-095a-4043-9ed0-9817b3a84c4e.jpg)

**Comment by hafedh-hichri** [comment]
Man I had a stroke for a sec
My brother in christ, this is not an issue 
![image](https://user-images.githubusercontent.com/70411813/220145138-6573c2e2-42ef-49d4-b5e2-e68fb5568c40.png)

**Comment by not-lain** [comment]
happy birthday @slimbaccouch 💖💖
